import { readFileSync } from "node:fs";
import { join } from "node:path";

export function getPackageVersion(): string {
  try {
    const packageJsonPath = join(
      process.cwd(),
      "node_modules",
      "hyper-pwt",
      "package.json",
    );
    const packageJson = JSON.parse(readFileSync(packageJsonPath, "utf-8"));

    return packageJson.version || "unknown";
  } catch {
    try {
      const currentDir = process.cwd();
      const packageJsonPath = join(currentDir, "package.json");
      const packageJson = JSON.parse(readFileSync(packageJsonPath, "utf-8"));

      if (packageJson.name === "hyper-pwt") {
        return packageJson.version || "unknown";
      }
    } catch {
      return "unknown";
    }
  }
}

export function generateHeaderComment(): string {
  const version = getPackageVersion();

  return `/**
 * This file was automatically generated by hyper-pwt v${version}
 * DO NOT MODIFY THIS FILE DIRECTLY
 * 
 * To regenerate this file, run the type generator with your widget XML file.
 * Any manual changes to this file will be lost when the types are regenerated.
 */

`;
}
